services:
  postgres:
    image: postgres:17
    container_name: incirecruta_postgres
    restart: always
    environment:
      POSTGRES_USER: incirecruta_user
      POSTGRES_DB: inci_recruta
      POSTGRES_PASSWORD: incirecruta1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: